---
abstract: 'acceptance tests for C<Future::IO> implementations'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires: {}
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Future-IO-Impl
provides:
  Test::Future::IO::Impl:
    file: lib/Test/Future/IO/Impl.pm
    version: '0.14'
requires:
  Errno: '0'
  IO::Handle: '0'
  Socket: '0'
  Test2::V0: '0'
  Time::HiRes: '0'
  perl: '5.014'
resources:
  license: http://dev.perl.org/licenses/
version: '0.14'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
